// Generated by ts-to-zod
import { z } from "zod";

export const daySchema = z.object({
  year: z.number(),
  month: z.number(),
  day: z.number(),
});

export const dayValueSchema = z.union([daySchema, z.undefined()]).nullable();
